spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8080/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:8881/
          predicates:
            - Path=/products/**
logging:
  level:
    root: debug
