services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=db_bot'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=root'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
