
package wsProxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "bankServiceWS", targetNamespace = "http://impl.ws.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServiceWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://impl.ws.org/", className = "wsProxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://impl.ws.org/", className = "wsProxy.ConvertResponse")
    @Action(input = "http://impl.ws.org/bankServiceWS/convertRequest", output = "http://impl.ws.org/bankServiceWS/convertResponse")
    public double convert(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsProxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://impl.ws.org/", className = "wsProxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://impl.ws.org/", className = "wsProxy.GetAccountResponse")
    @Action(input = "http://impl.ws.org/bankServiceWS/getAccountRequest", output = "http://impl.ws.org/bankServiceWS/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<wsProxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://impl.ws.org/", className = "wsProxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://impl.ws.org/", className = "wsProxy.GetAccountsResponse")
    @Action(input = "http://impl.ws.org/bankServiceWS/getAccountsRequest", output = "http://impl.ws.org/bankServiceWS/getAccountsResponse")
    public List<Account> getAccounts();

}
